In [1]:
import torch 
import numpy as np

In [2]:
data = [[1,2] , [3,4]]
x_data  = torch.tensor(data)
print(f"tensor tu list : \n {x_data}")

tensor tu list : 
 tensor([[1, 2],
        [3, 4]])


In [7]:
#tensor tu numpy arr 
np_array = np.array(data)
x_numpy = torch.from_numpy(np_array)
print(f"from nparr {x_numpy}")
x_numpy.shape

from nparr tensor([[1, 2],
        [3, 4]])


torch.Size([2, 2])

In [13]:
x_rand = torch.rand_like(x_data , dtype = torch.float)
print(f'random tensor {x_rand}')
if torch.cuda.is_available():
    x = x_rand.to("cuda")
    print(x.device)

random tensor tensor([[0.3671, 0.8513],
        [0.9160, 0.5408]])
cuda:0


In [21]:
tensor = torch.ones(4,4)
tensor = tensor.sum()
print(type(tensor) , tensor)
agg_item = tensor.item()
print(agg_item , type(agg_item))

<class 'torch.Tensor'> tensor(16.)
16.0 <class 'float'>


In [40]:
# task 2
x_data = torch.tensor([[1,2] , [3 ,4]])
sum = x_data * x_data 
mul = x_data @ x_data.T
x_data + 5

tensor([[6, 7],
        [8, 9]])

In [32]:
#task3 indexing vaf slicing 
print(x_data)
x_data[0 , :] # first row
col2 = x_data[: ,  1]
x_data[1,1]

tensor([[1, 2],
        [3, 4]])


tensor(4)

In [ ]:
#task4
one = torch.rand(4,4)
one.view(16)
one.reshape(16,1)

In [46]:
#auto gradient 

x = torch.ones(1 , requires_grad=True)
y = x+2
print(y.grad_fn)

z  = y*y*3
z.backward()
x.grad

tensor([18.])

In [58]:
#torch.nn 

linear_layer = torch.nn.Linear(in_features = 5 , out_features = 2)

input_tensor = torch.rand(3,1 ,5)
test_tensor = torch.rand(3,5)
output = linear_layer(input_tensor)
test_output = linear_layer(test_tensor)
print(test_output)
print(f"Output:\n {output}")

tensor([[ 0.0846,  0.0501],
        [ 0.0590,  0.1061],
        [-0.1147,  0.0264]], grad_fn=<AddmmBackward0>)
Output:
 tensor([[[-0.0790, -0.0269]],

        [[-0.1297,  0.2263]],

        [[ 0.1370, -0.0593]]], grad_fn=<ViewBackward0>)


In [60]:
#nn.embedding 

embedding_layer = torch.nn.Embedding(num_embeddings = 10 , embedding_dim = 3)
input_indices = torch.LongTensor([1,5,0,8])

embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")


Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.8322,  0.7662,  1.6541],
        [ 1.1454, -0.7966,  0.5027],
        [ 0.5263, -1.2882, -0.2835],
        [ 0.5004,  0.4754, -0.3918]], grad_fn=<EmbeddingBackward0>)


In [63]:
from torch import nn 

class MyFirstModel(nn.Module):
    def __init__(self , vocab_size , embedding_dim , hidden_dim , output_dim):
        super(MyFirstModel , self).__init__()
        self.embedding = nn.Embedding(vocab_size , embedding_dim)
        self.linear = nn.Linear(embedding_dim , hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim , output_dim)
    def forward(self , indices):
        embeds  = self.embedding(indices)

        hidden = self.activation(self.linear(embeds))

        output = self.output_layer(hidden)
        return output
model = MyFirstModel(vocab_size= 100 , embedding_dim= 16 , hidden_dim=8 , output_dim=2)
input_data = torch.LongTensor([1 , 3, 4, 9])

output_data= model(input_data)

output

tensor([[[-0.0790, -0.0269]],

        [[-0.1297,  0.2263]],

        [[ 0.1370, -0.0593]]], grad_fn=<ViewBackward0>)